version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./inventory.db:/app/inventory.db
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./inventory.db