"""Add index to product_id in stock_transactions

Revision ID: 0cc5057a83ea
Revises: fa21e079b292
Create Date: 2025-07-26 22:33:13.897079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cc5057a83ea'
down_revision: Union[str, Sequence[str], None] = 'fa21e079b292'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_stock_transactions_product_id'), 'stock_transactions', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_transactions_product_id'), table_name='stock_transactions')
    # ### end Alembic commands ###
